name:                extensional-plume
version:             0.1.0.0
github:              "Earl-Wu/haskell-odefa"
license:             BSD3
author:              "Earl Wu"
maintainer:          "example@example.com"
copyright:           "2021-2022 Earl Wu, Zachary Palmer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/helloworld#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- more-containers
- array
- bytestring
- dequeue
- deepseq
- directory
- filepath
- mtl >= 2.2.2
- tasty
- tasty-hunit
- time >= 1.8.0.2
- transformers >= 0.5.6.2


library:
  source-dirs: src

executables:
  extensional-plume-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - extensional-plume

tests:
  extensional-plume-test:
    main:                TestMain.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - extensional-plume
